# ---------- PYTHON INTRODUCTION ---------- #

# Python is an Interpreted High Level General Purpose Programming Language...
# It is very simple to learn / understand...
# It was created by 'Guido van Rossum', and first released on February 20, 1991...
# Python 2.0 was released in 2000 and Python 3.0 was released in 2008...
# Python is a dynamically-typed (No datatype required) Programming Language...
# It is an open source and completely free to use...
# It is a Platform independent Language (Windows / Linux / MacOS)...
# It supports multiple programming paradigms, including structured, object-oriented and functional programming...
# It has built-in Libraries/Modules and also supports external...

# ---------- FLAVOURS OF PYTHON ---------- #

# CPython: It is the standard flavor of Python. It can be used to work with C language Applications...
# Jython OR JPython: It is for Java Applications. It can run on JVM...
# IronPython: It is for C#.Net platform...
# PyPy: The main advantage of PyPy is performance will be improved because JIT compiler is available inside PVM...
# RubyPython For Ruby Platforms...
# AnacondaPython: It is specially designed for handling large volume of data processing...

# ---------- First Python Program ---------- #

name = "Hello World!"
print(name)

# ---------- End of File ---------- #
