# ---------- Variables in Python ---------- #

# Variables are containers for storing data value / values...
# Python has no command for declaring a variable...
# A variable is created the moment you first assign a value to it...
# Variable  do not need to be declared with any particular type...
# A variable can even change type after they have been set...
# Variables are case sensitive...
# String variables can be declared either by using single or double quotes...
# Variable name should not start with numbers...
# A variable name may only contain (0-9), (A-Z), (a-z) and underscore(_)...
# A variable name should not contain spaces...

x = 4  # Data type not specified, it will automatically finds as int...
print(x)
a = "Green"  # Variable in small letter... String given inside double quotes...
print(a)
A = 'Ragu'  # Variable in capital letter... String given inside single quotes...
print(A)

# ---------- Type Casting in Python ---------- #

# If you want to specify the data type of a variable, this can be done with casting...

x = str(3)
y = int(3)
z = float(3)
print(x)
print(y)
print(z)

# ---------- Getting the Type ---------- #

# You can get the data type of a variable with the type() function...

x = 5
y = 3.5
z = "John"
print(type(x))
print(type(y))
print(type(z))

# ---------- End of File ---------- #
